name: 🚀 Deploy via SFTP to Hostinger

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    name: 🎉 SFTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files via SFTP
        uses: pressidium/sftp-deploy@v1
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          user: ${{ secrets.SFTP_USER }}
          pass: ${{ secrets.SFTP_PASS }}
          local_path: './'
          remote_path: '/domains/golstalgia.com/public_html/'
          exclude: |
            .git*
            node_modules
            docker
            docker-compose.yml
            .env
            README.md
            *.sqlite
            *.zip
            database/migrations
            .ftp-deploy-sync-state.json
